import SwiftUI
import shared  // KMP Compose Multiplatform framework

/// Hosts the Kotlin Multiplatform Compose UI.
struct ContentView: View {
    var body: some View {
        ComposeView()
            .ignoresSafeArea(.keyboard)
    }
}

/// Bridges Compose Multiplatform UIViewController into SwiftUI.
struct ComposeView: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        // MainViewControllerKt is generated by KMP for iOS entry points.
        MainViewControllerKt.MainViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}
